<?php

namespace AppBundle\Repository;

/**
 * NutritionalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutritionalInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
